part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

class GiveawayApi {
  final GiveawayApiDelegate apiDelegate;

  GiveawayApi(ApiClient apiClient) : apiDelegate = GiveawayApiDelegate(apiClient);

  Future<Giveaway> getGiveaways({Options? options}) async {
    final response = await apiDelegate.getGiveaways(
      options: options,
    );

    final __body = response.body;
    if (response.statusCode >= 400) {
      throw ApiException(response.statusCode, __body == null ? null : await decodeBodyBytes(__body));
    }

    if (__body == null) {
      throw ApiException(500, 'Received an empty body (not in a 204)');
    }

    return await apiDelegate.getGiveaways_decode(__body);
  }
}

class GiveawayApiDelegate {
  final ApiClient apiClient;

  GiveawayApiDelegate(this.apiClient);

  Future<ApiResponse> getGiveaways({Options? options}) async {
    // create path and map variables
    final __path = '/giveaway';

    // query params
    final queryParams = <QueryParam>[];
    final headerParams = <String, String>{}..addAll(options?.headers?.cast<String, String>() ?? {});
    if (!headerParams.containsKey('Accept')) {
      // we only want to accept this format as we can parse it
      headerParams['Accept'] = 'application/json';
    }

    final authNames = <String>['oauth2'];
    final opt = options ?? Options();

    final contentTypes = [];

    if (contentTypes.isNotEmpty && headerParams['Content-Type'] == null) {
      headerParams['Content-Type'] = contentTypes[0];
    }

    headerParams.removeWhere((key, value) => value.isEmpty); // remove empty headers
    opt.headers = headerParams;
    opt.method = 'GET';

    return await apiClient.invokeAPI(__path, queryParams, null, authNames, opt);
  }

  Future<Giveaway> getGiveaways_decode(Stream<List<int>> body) async {
    return LocalApiClient.deserializeFromString(await utf8.decodeStream(body), 'Giveaway') as Giveaway;
  }
}
