name: komm_api
version: 1.0.0
description: Komm Api

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  dio: '^4.0.0'
  openapi_dart_common: ^4.1.1
  collection: '^1.15.0'
dev_dependencies:
  test: ^1.3.0
  analyzer: ^0.40.7

