part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// BlockUserRequest
class BlockUserRequest {
  String? mainProfile;

  String? blockProfile;

  BlockUserRequest({
    this.mainProfile,
    this.blockProfile,
  });

  @override
  String toString() {
    return 'BlockUserRequest[mainProfile=$mainProfile, blockProfile=$blockProfile, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    mainProfile = (json[r'mainProfile'] == null)
        ? null
        : (json[r'mainProfile'] as String?);

    blockProfile = (json[r'blockProfile'] == null)
        ? null
        : (json[r'blockProfile'] as String?);
  }

  BlockUserRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (mainProfile != null) {
      json[r'mainProfile'] = mainProfile;
    }
    if (blockProfile != null) {
      json[r'blockProfile'] = blockProfile;
    }
    return json;
  }

  static List<BlockUserRequest> listFromJson(List<dynamic>? json) {
    return json == null
        ? <BlockUserRequest>[]
        : json.map((value) => BlockUserRequest.fromJson(value)).toList();
  }

  static Map<String, BlockUserRequest> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, BlockUserRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = BlockUserRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is BlockUserRequest && runtimeType == __other.runtimeType) {
      return mainProfile == __other.mainProfile &&
          blockProfile == __other.blockProfile;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (mainProfile != null) {
      hashCode = hashCode * 31 + mainProfile.hashCode;
    }

    if (blockProfile != null) {
      hashCode = hashCode * 31 + blockProfile.hashCode;
    }

    return hashCode;
  }

  BlockUserRequest copyWith({
    String? mainProfile,
    String? blockProfile,
  }) {
    mainProfile ??= this.mainProfile;
    blockProfile ??= this.blockProfile;

    final _copy_mainProfile = mainProfile;
    final _copy_blockProfile = blockProfile;

    return BlockUserRequest(
      mainProfile: _copy_mainProfile,
      blockProfile: _copy_blockProfile,
    );
  }
}
