part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// contactKomm_request
class ContactKommRequest {
  String? profileId;

  String? type;

  String? message;

  ContactKommRequest({
    this.profileId,
    this.type,
    this.message,
  });

  @override
  String toString() {
    return 'ContactKommRequest[profileId=$profileId, type=$type, message=$message, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    profileId = (json[r'profileId'] == null) ? null : (json[r'profileId'] as String?);

    type = (json[r'type'] == null) ? null : (json[r'type'] as String?);

    message = (json[r'message'] == null) ? null : (json[r'message'] as String?);
  }

  ContactKommRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (profileId != null) {
      json[r'profileId'] = profileId;
    }
    if (type != null) {
      json[r'type'] = type;
    }
    if (message != null) {
      json[r'message'] = message;
    }
    return json;
  }

  static List<ContactKommRequest> listFromJson(List<dynamic>? json) {
    return json == null ? <ContactKommRequest>[] : json.map((value) => ContactKommRequest.fromJson(value)).toList();
  }

  static Map<String, ContactKommRequest> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, ContactKommRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) => map[key] = ContactKommRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is ContactKommRequest && runtimeType == __other.runtimeType) {
      return profileId == __other.profileId && type == __other.type && message == __other.message;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (profileId != null) {
      hashCode = hashCode * 31 + profileId.hashCode;
    }

    if (type != null) {
      hashCode = hashCode * 31 + type.hashCode;
    }

    if (message != null) {
      hashCode = hashCode * 31 + message.hashCode;
    }

    return hashCode;
  }

  ContactKommRequest copyWith({
    String? profileId,
    String? type,
    String? message,
  }) {
    profileId ??= this.profileId;
    type ??= this.type;
    message ??= this.message;

    final _copy_profileId = profileId;
    final _copy_type = type;
    final _copy_message = message;

    return ContactKommRequest(
      profileId: _copy_profileId,
      type: _copy_type,
      message: _copy_message,
    );
  }
}
