part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// createPoi_request
class CreatePoiRequest {
  String? id;

  String? profile;

  String? alias;

  String? coordinates;

  CreatePoiRequest({
    this.id,
    this.profile,
    this.alias,
    this.coordinates,
  });

  @override
  String toString() {
    return 'CreatePoiRequest[id=$id, profile=$profile, alias=$alias, coordinates=$coordinates, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    id = (json[r'id'] == null) ? null : (json[r'id'] as String?);

    profile = (json[r'profile'] == null) ? null : (json[r'profile'] as String?);

    alias = (json[r'alias'] == null) ? null : (json[r'alias'] as String?);

    coordinates = (json[r'coordinates'] == null)
        ? null
        : (json[r'coordinates'] as String?);
  }

  CreatePoiRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (id != null) {
      json[r'id'] = id;
    }
    if (profile != null) {
      json[r'profile'] = profile;
    }
    if (alias != null) {
      json[r'alias'] = alias;
    }
    if (coordinates != null) {
      json[r'coordinates'] = coordinates;
    }
    return json;
  }

  static List<CreatePoiRequest> listFromJson(List<dynamic>? json) {
    return json == null
        ? <CreatePoiRequest>[]
        : json.map((value) => CreatePoiRequest.fromJson(value)).toList();
  }

  static Map<String, CreatePoiRequest> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, CreatePoiRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = CreatePoiRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is CreatePoiRequest && runtimeType == __other.runtimeType) {
      return id == __other.id &&
          profile == __other.profile &&
          alias == __other.alias &&
          coordinates == __other.coordinates;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (id != null) {
      hashCode = hashCode * 31 + id.hashCode;
    }

    if (profile != null) {
      hashCode = hashCode * 31 + profile.hashCode;
    }

    if (alias != null) {
      hashCode = hashCode * 31 + alias.hashCode;
    }

    if (coordinates != null) {
      hashCode = hashCode * 31 + coordinates.hashCode;
    }

    return hashCode;
  }

  CreatePoiRequest copyWith({
    String? id,
    String? profile,
    String? alias,
    String? coordinates,
  }) {
    id ??= this.id;
    profile ??= this.profile;
    alias ??= this.alias;
    coordinates ??= this.coordinates;

    final _copy_id = id;
    final _copy_profile = profile;
    final _copy_alias = alias;
    final _copy_coordinates = coordinates;

    return CreatePoiRequest(
      id: _copy_id,
      profile: _copy_profile,
      alias: _copy_alias,
      coordinates: _copy_coordinates,
    );
  }
}
