part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// Education
class Education {
  /* Identifier of the object */
  String? id;

  String? name;

  String? description;

  Education({
    this.id,
    this.name,
    this.description,
  });

  @override
  String toString() {
    return 'Education[id=$id, name=$name, description=$description, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    id = (json[r'id'] == null) ? null : (json[r'id'] as String?);

    name = (json[r'name'] == null) ? null : (json[r'name'] as String?);

    description = (json[r'description'] == null)
        ? null
        : (json[r'description'] as String?);
  }

  Education.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (id != null) {
      json[r'id'] = id;
    }
    if (name != null) {
      json[r'name'] = name;
    }
    if (description != null) {
      json[r'description'] = description;
    }
    return json;
  }

  static List<Education> listFromJson(List<dynamic>? json) {
    return json == null
        ? <Education>[]
        : json.map((value) => Education.fromJson(value)).toList();
  }

  static Map<String, Education> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, Education>{};
    if (json != null && json.isNotEmpty) {
      json.forEach(
          (String key, dynamic value) => map[key] = Education.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is Education && runtimeType == __other.runtimeType) {
      return id == __other.id &&
          name == __other.name &&
          description == __other.description;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (id != null) {
      hashCode = hashCode * 31 + id.hashCode;
    }

    if (name != null) {
      hashCode = hashCode * 31 + name.hashCode;
    }

    if (description != null) {
      hashCode = hashCode * 31 + description.hashCode;
    }

    return hashCode;
  }

  Education copyWith({
    String? id,
    String? name,
    String? description,
  }) {
    id ??= this.id;
    name ??= this.name;
    description ??= this.description;

    final _copy_id = id;
    final _copy_name = name;
    final _copy_description = description;

    return Education(
      id: _copy_id,
      name: _copy_name,
      description: _copy_description,
    );
  }
}
