part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// ErrorResponse
class ErrorResponse {
  /* Description of error */
  String? message;

  ErrorResponse({
    this.message,
  });

  @override
  String toString() {
    return 'ErrorResponse[message=$message, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    message = (json[r'message'] == null) ? null : (json[r'message'] as String?);
  }

  ErrorResponse.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (message != null) {
      json[r'message'] = message;
    }
    return json;
  }

  static List<ErrorResponse> listFromJson(List<dynamic>? json) {
    return json == null ? <ErrorResponse>[] : json.map((value) => ErrorResponse.fromJson(value)).toList();
  }

  static Map<String, ErrorResponse> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, ErrorResponse>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) => map[key] = ErrorResponse.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is ErrorResponse && runtimeType == __other.runtimeType) {
      return message == __other.message;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (message != null) {
      hashCode = hashCode * 31 + message.hashCode;
    }

    return hashCode;
  }

  ErrorResponse copyWith({
    String? message,
  }) {
    message ??= this.message;

    final _copy_message = message;

    return ErrorResponse(
      message: _copy_message,
    );
  }
}
