part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// EventCheckIn
class EventCheckIn {
  /* Event Id */
  String? id;
  /* Organizer coordinates */
  String? location;

  EventCheckIn({
    this.id,
    this.location,
  });

  @override
  String toString() {
    return 'EventCheckIn[id=$id, location=$location, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    id = (json[r'id'] == null) ? null : (json[r'id'] as String?);

    location =
        (json[r'location'] == null) ? null : (json[r'location'] as String?);
  }

  EventCheckIn.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (id != null) {
      json[r'id'] = id;
    }
    if (location != null) {
      json[r'location'] = location;
    }
    return json;
  }

  static List<EventCheckIn> listFromJson(List<dynamic>? json) {
    return json == null
        ? <EventCheckIn>[]
        : json.map((value) => EventCheckIn.fromJson(value)).toList();
  }

  static Map<String, EventCheckIn> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, EventCheckIn>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = EventCheckIn.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is EventCheckIn && runtimeType == __other.runtimeType) {
      return id == __other.id && location == __other.location;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (id != null) {
      hashCode = hashCode * 31 + id.hashCode;
    }

    if (location != null) {
      hashCode = hashCode * 31 + location.hashCode;
    }

    return hashCode;
  }

  EventCheckIn copyWith({
    String? id,
    String? location,
  }) {
    id ??= this.id;
    location ??= this.location;

    final _copy_id = id;
    final _copy_location = location;

    return EventCheckIn(
      id: _copy_id,
      location: _copy_location,
    );
  }
}
