part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// _event__eventId__delete_request
class EventEventIdDeleteRequest {
  String? profile;
  String? title;
  String? description;
  String? descriptionShort;
  String? date;
  String? hourInit;
  String? hourEnd;
  num?    price;
  int?    paxes;
  String? location;
  int?    sendToBlocked;
  int?    requestValuation;
  int?    filterToPreferences;

  EventEventIdDeleteRequest({
    this.profile,
    this.title,
    this.description,
    this.descriptionShort,
    this.date,
    this.hourInit,
    this.hourEnd,
    this.price,
    this.paxes,
    this.location,
    this.sendToBlocked,
    this.requestValuation,
    this.filterToPreferences,
  });

  @override
  String toString() {
    return 'EventEventIdDeleteRequest[profile=$profile, title=$title, description=$description, descriptionShort=$descriptionShort, date=$date, hourInit=$hourInit, hourEnd=$hourEnd, price=$price, paxes=$paxes, location=$location, sendToBlocked=$sendToBlocked, requestValuation=$requestValuation, filterToPreferences=$filterToPreferences, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    profile             = (json[r'profile']               == null) ? null: (json[r'profile'] as String?);
    title               = (json[r'title']                 == null) ? null: (json[r'title'] as String?);
    description         = (json[r'description']           == null) ? null: (json[r'description'] as String?);
    descriptionShort    = (json[r'description_short']     == null) ? null: (json[r'description_short'] as String?);
    date                = (json[r'date']                  == null) ? null: (json[r'date'] as String?);
    hourInit            = (json[r'hour_init']             == null) ? null: (json[r'hour_init'] as String?);
    hourEnd             = (json[r'hour_end']              == null) ? null: (json[r'hour_end'] as String?);
    price               = (json[r'price']                 == null) ? null: (json[r'price'] as num?);
    paxes               = (json[r'paxes']                 == null) ? null: (json[r'paxes'] as int?);
    location            = (json[r'location']              == null) ? null: (json[r'location'] as String?);
    sendToBlocked       = (json[r'send_to_blocked']       == null) ? null: (json[r'send_to_blocked'] as int?);
    requestValuation    = (json[r'request_valuation']     == null) ? null: (json[r'request_valuation'] as int?);
    filterToPreferences = (json[r'filter_to_preferences'] == null) ? null: (json[r'filter_to_preferences'] as int?);
  }

  EventEventIdDeleteRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (profile != null) {
      json[r'profile'] = profile;
    }
    if (title != null) {
      json[r'title'] = title;
    }
    if (description != null) {
      json[r'description'] = description;
    }
    if (descriptionShort != null) {
      json[r'description_short'] = descriptionShort;
    }
    if (date != null) {
      json[r'date'] = date;
    }
    if (hourInit != null) {
      json[r'hour_init'] = hourInit;
    }
    if (hourEnd != null) {
      json[r'hour_end'] = hourEnd;
    }
    if (price != null) {
      json[r'price'] = price;
    }
    if (paxes != null) {
      json[r'paxes'] = paxes;
    }
    if (location != null) {
      json[r'location'] = location;
    }
    if (sendToBlocked != null) {
      json[r'send_to_blocked'] = sendToBlocked;
    }
    if (requestValuation != null) {
      json[r'request_valuation'] = requestValuation;
    }
    if (filterToPreferences != null) {
      json[r'filter_to_preferences'] = filterToPreferences;
    }
    return json;
  }

  static List<EventEventIdDeleteRequest> listFromJson(List<dynamic>? json) {
    return json == null
        ? <EventEventIdDeleteRequest>[]
        : json.map((value) => EventEventIdDeleteRequest.fromJson(value)).toList();
  }

  static Map<String, EventEventIdDeleteRequest> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, EventEventIdDeleteRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) => map[key] = EventEventIdDeleteRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is EventEventIdDeleteRequest && runtimeType == __other.runtimeType) {
      return profile == __other.profile &&
          title == __other.title &&
          description == __other.description &&
          descriptionShort == __other.descriptionShort &&
          date == __other.date &&
          hourInit == __other.hourInit &&
          hourEnd == __other.hourEnd &&
          price == __other.price &&
          paxes == __other.paxes &&
          location == __other.location &&
          sendToBlocked == __other.sendToBlocked &&
          requestValuation == __other.requestValuation &&
          filterToPreferences == __other.filterToPreferences;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (profile != null) {
      hashCode = hashCode * 31 + profile.hashCode;
    }

    if (title != null) {
      hashCode = hashCode * 31 + title.hashCode;
    }

    if (description != null) {
      hashCode = hashCode * 31 + description.hashCode;
    }

    if (descriptionShort != null) {
      hashCode = hashCode * 31 + descriptionShort.hashCode;
    }

    if (date != null) {
      hashCode = hashCode * 31 + date.hashCode;
    }

    if (hourInit != null) {
      hashCode = hashCode * 31 + hourInit.hashCode;
    }

    if (hourEnd != null) {
      hashCode = hashCode * 31 + hourEnd.hashCode;
    }

    if (price != null) {
      hashCode = hashCode * 31 + price.hashCode;
    }

    if (paxes != null) {
      hashCode = hashCode * 31 + paxes.hashCode;
    }

    if (location != null) {
      hashCode = hashCode * 31 + location.hashCode;
    }

    if (sendToBlocked != null) {
      hashCode = hashCode * 31 + sendToBlocked.hashCode;
    }

    if (requestValuation != null) {
      hashCode = hashCode * 31 + requestValuation.hashCode;
    }

    if (filterToPreferences != null) {
      hashCode = hashCode * 31 + filterToPreferences.hashCode;
    }

    return hashCode;
  }

  EventEventIdDeleteRequest copyWith({
    String? profile,
    String? title,
    String? description,
    String? descriptionShort,
    String? date,
    String? hourInit,
    String? hourEnd,
    num? price,
    int? paxes,
    String? location,
    int? sendToBlocked,
    int? requestValuation,
    int? filterToPreferences,
  }) {
    profile ??= this.profile;
    title ??= this.title;
    description ??= this.description;
    descriptionShort ??= this.descriptionShort;
    date ??= this.date;
    hourInit ??= this.hourInit;
    hourEnd ??= this.hourEnd;
    price ??= this.price;
    paxes ??= this.paxes;
    location ??= this.location;
    sendToBlocked ??= this.sendToBlocked;
    requestValuation ??= this.requestValuation;
    filterToPreferences ??= this.filterToPreferences;

    final _copy_profile = profile;
    final _copy_title = title;
    final _copy_description = description;
    final _copy_descriptionShort = descriptionShort;
    final _copy_date = date;
    final _copy_hourInit = hourInit;
    final _copy_hourEnd = hourEnd;
    final _copy_price = price;
    final _copy_paxes = paxes;
    final _copy_location = location;
    final _copy_sendToBlocked = sendToBlocked;
    final _copy_requestValuation = requestValuation;
    final _copy_filterToPreferences = filterToPreferences;

    return EventEventIdDeleteRequest(
      profile: _copy_profile,
      title: _copy_title,
      description: _copy_description,
      descriptionShort: _copy_descriptionShort,
      date: _copy_date,
      hourInit: _copy_hourInit,
      hourEnd: _copy_hourEnd,
      price: _copy_price,
      paxes: _copy_paxes,
      location: _copy_location,
      sendToBlocked: _copy_sendToBlocked,
      requestValuation: _copy_requestValuation,
      filterToPreferences: _copy_filterToPreferences,
    );
  }
}
