part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// Genre
class Gender {
  /* Identifier of the object */
  String? id;

  String? name;

  Gender({
    this.id,
    this.name,
  });

  factory Gender.binary() => Gender(id: "ec0d7620-52e4-4f97-a1f8-5304479422c4", name: "No binario");

  @override
  String toString() {
    return 'Gender[id=$id, name=$name, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    id = (json[r'id'] == null) ? null : (json[r'id'] as String?);

    name = (json[r'name'] == null) ? null : (json[r'name'] as String?);
  }

  Gender.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (id != null) {
      json[r'id'] = id;
    }
    if (name != null) {
      json[r'name'] = name;
    }
    return json;
  }

  static List<Gender> listFromJson(List<dynamic>? json) {
    return json == null ? <Gender>[] : json.map((value) => Gender.fromJson(value)).toList();
  }

  static Map<String, Gender> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, Gender>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) => map[key] = Gender.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is Gender && runtimeType == __other.runtimeType) {
      return id == __other.id && name == __other.name;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (id != null) {
      hashCode = hashCode * 31 + id.hashCode;
    }

    if (name != null) {
      hashCode = hashCode * 31 + name.hashCode;
    }

    return hashCode;
  }

  Gender copyWith({
    String? id,
    String? name,
  }) {
    id ??= this.id;
    name ??= this.name;

    final _copy_id = id;
    final _copy_name = name;

    return Gender(
      id: _copy_id,
      name: _copy_name,
    );
  }
}
