part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// Poi
class Poi {
  String? id;
  String? alias;
  String? coordinates;
  bool? home;

  Poi({
    this.id,
    this.alias,
    this.coordinates,
    this.home,
  });

  @override
  String toString() {
    return 'Poi[id=$id, alias=$alias, coordinates=$coordinates, home=$home, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    id = (json[r'id'] == null) ? null : (json[r'id'] as String?);

    alias = (json[r'alias'] == null) ? null : (json[r'alias'] as String?);

    coordinates = (json[r'coordinates'] == null)
        ? null
        : (json[r'coordinates'] as String?);

    home = (json[r'home'] == null ? null : (json[r'home'] as bool?));
  }

  Poi.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (id != null) {
      json[r'id'] = id;
    }
    if (alias != null) {
      json[r'alias'] = alias;
    }
    if (coordinates != null) {
      json[r'coordinates'] = coordinates;
    }
    if (home != null) {
      json[r'home'] = home;

    }
    return json;
  }

  static List<Poi> listFromJson(List<dynamic>? json) {
    return json == null
        ? <Poi>[]
        : json.map((value) => Poi.fromJson(value)).toList();
  }

  static Map<String, Poi> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, Poi>{};
    if (json != null && json.isNotEmpty) {
      json.forEach(
          (String key, dynamic value) => map[key] = Poi.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is Poi && runtimeType == __other.runtimeType) {
      return id == __other.id &&
          alias == __other.alias &&
          coordinates == __other.coordinates &&
	  home == __other.home;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (id != null) {
      hashCode = hashCode * 31 + id.hashCode;
    }

    if (alias != null) {
      hashCode = hashCode * 31 + alias.hashCode;
    }

    if (coordinates != null) {
      hashCode = hashCode * 31 + coordinates.hashCode;
    }

    if (home != null) {
      hashCode = hashCode * 31 + home.hashCode;
    }

    return hashCode;
  }

  Poi copyWith({
    String? id,
    String? alias,
    String? coordinates,
    bool? home,
  }) {
    id ??= this.id;
    alias ??= this.alias;
    coordinates ??= this.coordinates;
    home ??= this.home;

    final _copy_id = id;
    final _copy_alias = alias;
    final _copy_coordinates = coordinates;
    final _copy_home = home;

    return Poi(
      id: _copy_id,
      alias: _copy_alias,
      coordinates: _copy_coordinates,
      home: _copy_home,
    );
  }
}
