part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// RateParticipantRequest
class RateParticipantRequest {
  String? id;

  String? profile;

  int? score;

  String? comment;

  RateParticipantRequest({
    this.id,
    this.profile,
    this.score,
    this.comment,
  });

  @override
  String toString() {
    return 'RateParticipantRequest[id=$id, profile=$profile, score=$score, comment=$comment, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    id = (json[r'id'] == null) ? null : (json[r'id'] as String?);

    profile = (json[r'profile'] == null) ? null : (json[r'profile'] as String?);

    score = (json[r'score'] == null) ? null : (json[r'score'] as int?);

    comment = (json[r'comment'] == null) ? null : (json[r'comment'] as String?);
  }

  RateParticipantRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (id != null) {
      json[r'id'] = id;
    }
    if (profile != null) {
      json[r'profile'] = profile;
    }
    if (score != null) {
      json[r'score'] = score;
    }
    if (comment != null) {
      json[r'comment'] = comment;
    }
    return json;
  }

  static List<RateParticipantRequest> listFromJson(List<dynamic>? json) {
    return json == null
        ? <RateParticipantRequest>[]
        : json.map((value) => RateParticipantRequest.fromJson(value)).toList();
  }

  static Map<String, RateParticipantRequest> mapFromJson(
      Map<String, dynamic>? json) {
    final map = <String, RateParticipantRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = RateParticipantRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is RateParticipantRequest &&
        runtimeType == __other.runtimeType) {
      return id == __other.id &&
          profile == __other.profile &&
          score == __other.score &&
          comment == __other.comment;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (id != null) {
      hashCode = hashCode * 31 + id.hashCode;
    }

    if (profile != null) {
      hashCode = hashCode * 31 + profile.hashCode;
    }

    if (score != null) {
      hashCode = hashCode * 31 + score.hashCode;
    }

    if (comment != null) {
      hashCode = hashCode * 31 + comment.hashCode;
    }

    return hashCode;
  }

  RateParticipantRequest copyWith({
    String? id,
    String? profile,
    int? score,
    String? comment,
  }) {
    id ??= this.id;
    profile ??= this.profile;
    score ??= this.score;
    comment ??= this.comment;

    final _copy_id = id;
    final _copy_profile = profile;
    final _copy_score = score;
    final _copy_comment = comment;

    return RateParticipantRequest(
      id: _copy_id,
      profile: _copy_profile,
      score: _copy_score,
      comment: _copy_comment,
    );
  }
}
