part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// ReadNotificationRequest
class ReadNotificationRequest {
  String? type;

  ReadNotificationRequest({
    this.type,
  });

  @override
  String toString() {
    return 'ReadNotificationRequest[type=$type, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    type = (json[r'type'] == null) ? null : (json[r'type'] as String?);
  }

  ReadNotificationRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (type != null) {
      json[r'type'] = type;
    }
    return json;
  }

  static List<ReadNotificationRequest> listFromJson(List<dynamic>? json) {
    return json == null
        ? <ReadNotificationRequest>[]
        : json.map((value) => ReadNotificationRequest.fromJson(value)).toList();
  }

  static Map<String, ReadNotificationRequest> mapFromJson(
      Map<String, dynamic>? json) {
    final map = <String, ReadNotificationRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = ReadNotificationRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is ReadNotificationRequest &&
        runtimeType == __other.runtimeType) {
      return type == __other.type;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (type != null) {
      hashCode = hashCode * 31 + type.hashCode;
    }

    return hashCode;
  }

  ReadNotificationRequest copyWith({
    String? type,
  }) {
    type ??= this.type;

    final _copy_type = type;

    return ReadNotificationRequest(
      type: _copy_type,
    );
  }
}
