part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// RecoverPasswordValidRequest
class RecoverPasswordValidRequest {
  String? code;

  RecoverPasswordValidRequest({
    this.code,
  });

  @override
  String toString() {
    return 'RecoverPasswordValidRequest[code=$code, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    code = (json[r'code'] == null) ? null : (json[r'code'] as String?);
  }

  RecoverPasswordValidRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (code != null) {
      json[r'code'] = code;
    }
    return json;
  }

  static List<RecoverPasswordValidRequest> listFromJson(List<dynamic>? json) {
    return json == null
        ? <RecoverPasswordValidRequest>[]
        : json
            .map((value) => RecoverPasswordValidRequest.fromJson(value))
            .toList();
  }

  static Map<String, RecoverPasswordValidRequest> mapFromJson(
      Map<String, dynamic>? json) {
    final map = <String, RecoverPasswordValidRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = RecoverPasswordValidRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is RecoverPasswordValidRequest &&
        runtimeType == __other.runtimeType) {
      return code == __other.code;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (code != null) {
      hashCode = hashCode * 31 + code.hashCode;
    }

    return hashCode;
  }

  RecoverPasswordValidRequest copyWith({
    String? code,
  }) {
    code ??= this.code;

    final _copy_code = code;

    return RecoverPasswordValidRequest(
      code: _copy_code,
    );
  }
}
