part of komm.api;


// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// RecoverPasswordChangeRequest
class RecoverPasswordChangeRequest {
  String? id;

  String? password;

  RecoverPasswordChangeRequest({
    this.id,
    this.password,
  });

  @override
  String toString() {
    return 'RecoverPasswordChangeRequest[id=$id, password=$password, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    id = (json[r'id'] == null) ? null : (json[r'id'] as String?);

    password = (json[r'password'] == null) ? null : (json[r'password'] as String?);
  }

  RecoverPasswordChangeRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (id != null) {
      json[r'id'] = id;
    }
    if (password != null) {
      json[r'password'] = password;
    }
    return json;
  }

  static List<RecoverPasswordChangeRequest> listFromJson(List<dynamic>? json) {
    return json == null
        ? <RecoverPasswordChangeRequest>[]
        : json.map((value) => RecoverPasswordChangeRequest.fromJson(value)).toList();
  }

  static Map<String, RecoverPasswordChangeRequest> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, RecoverPasswordChangeRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) => map[key] = RecoverPasswordChangeRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is RecoverPasswordChangeRequest && runtimeType == __other.runtimeType) {
      return id == __other.id && password == __other.password;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (id != null) {
      hashCode = hashCode * 31 + id.hashCode;
    }

    if (password != null) {
      hashCode = hashCode * 31 + password.hashCode;
    }

    return hashCode;
  }

  RecoverPasswordChangeRequest copyWith({
    String? id,
    String? password,
  }) {
    id ??= this.id;
    password ??= this.password;

    final _copy_id = id;
    final _copy_password = password;

    return RecoverPasswordChangeRequest(
      id: _copy_id,
      password: _copy_password,
    );
  }
}
