part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// RequestRelationBody
class RequestRelationBody {
  String? id;
  String? fromProfile;
  String? toProfile;

  RequestRelationBody({
    this.id,
    this.fromProfile,
    this.toProfile,
  });

  @override
  String toString() {
    return 'RequestRelationBody[id=$id, fromProfile=$fromProfile, toProfile=$toProfile, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    id          = (json[r'id']           == null) ? null: (json[r'id'] as String?);
    fromProfile = (json[r'from_profile'] == null) ? null: (json[r'from_profile'] as String?);
    toProfile   = (json[r'to_profile']   == null) ? null: (json[r'to_profile'] as String?);
  }

  RequestRelationBody.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (id != null) {
      json[r'id'] = id;
    }
    if (fromProfile != null) {
      json[r'from_profile'] = fromProfile;
    }
    if (toProfile != null) {
      json[r'to_profile'] = toProfile;
    }
    return json;
  }

  static List<RequestRelationBody> listFromJson(List<dynamic>? json) {
    return json == null ? <RequestRelationBody>[] : json.map((value) => RequestRelationBody.fromJson(value)).toList();
  }

  static Map<String, RequestRelationBody> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, RequestRelationBody>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) => map[key] = RequestRelationBody.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is RequestRelationBody && runtimeType == __other.runtimeType) {
      return id == __other.id && fromProfile == __other.fromProfile && toProfile == __other.toProfile;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (id != null) {
      hashCode = hashCode * 31 + id.hashCode;
    }

    if (fromProfile != null) {
      hashCode = hashCode * 31 + fromProfile.hashCode;
    }

    if (toProfile != null) {
      hashCode = hashCode * 31 + toProfile.hashCode;
    }

    return hashCode;
  }

  RequestRelationBody copyWith({
    String? id,
    String? fromProfile,
    String? toProfile,
  }) {
    id          ??= this.id;
    fromProfile ??= this.fromProfile;
    toProfile   ??= this.toProfile;

    final _copy_id = id;
    final _copy_fromProfile = fromProfile;
    final _copy_toProfile = toProfile;

    return RequestRelationBody(
      id: _copy_id,
      fromProfile: _copy_fromProfile,
      toProfile: _copy_toProfile,
    );
  }
}
