part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// RequestRelationBody_1
class ResponseRelationBody {
  String? id;

  /* 0 for reject, 1 for accept */
  int? response;

  ResponseRelationBody({
    this.id,
    this.response,
  });

  @override
  String toString() {
    return 'RequestRelationBody1[id=$id, response=$response, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    id = (json[r'id'] == null) ? null : (json[r'id'] as String?);

    response = (json[r'response'] == null) ? null : (json[r'response'] as int?);
  }

  ResponseRelationBody.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (id != null) {
      json[r'id'] = id;
    }
    if (response != null) {
      json[r'response'] = response;
    }
    return json;
  }

  static List<ResponseRelationBody> listFromJson(List<dynamic>? json) {
    return json == null ? <ResponseRelationBody>[] : json.map((value) => ResponseRelationBody.fromJson(value)).toList();
  }

  static Map<String, ResponseRelationBody> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, ResponseRelationBody>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) => map[key] = ResponseRelationBody.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is ResponseRelationBody && runtimeType == __other.runtimeType) {
      return id == __other.id && response == __other.response;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (id != null) {
      hashCode = hashCode * 31 + id.hashCode;
    }

    if (response != null) {
      hashCode = hashCode * 31 + response.hashCode;
    }

    return hashCode;
  }

  ResponseRelationBody copyWith({
    String? id,
    int? response,
  }) {
    id ??= this.id;
    response ??= this.response;

    final _copy_id = id;
    final _copy_response = response;

    return ResponseRelationBody(
      id: _copy_id,
      response: _copy_response,
    );
  }
}
