part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// SignInResponse
class SignInResponse {
  /* This is the primary identifier for this object.  */
  String? id;

  String? email;

  String? secret;

  SignInResponse({
    this.id,
    this.email,
    this.secret,
  });

  @override
  String toString() {
    return 'SignInResponse[id=$id, email=$email, secret=$secret, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    id = (json[r'id'] == null) ? null : (json[r'id'] as String?);

    email = (json[r'email'] == null) ? null : (json[r'email'] as String?);

    secret = (json[r'secret'] == null) ? null : (json[r'secret'] as String?);
  }

  SignInResponse.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (id != null) {
      json[r'id'] = id;
    }
    if (email != null) {
      json[r'email'] = email;
    }
    if (secret != null) {
      json[r'secret'] = secret;
    }
    return json;
  }

  static List<SignInResponse> listFromJson(List<dynamic>? json) {
    return json == null
        ? <SignInResponse>[]
        : json.map((value) => SignInResponse.fromJson(value)).toList();
  }

  static Map<String, SignInResponse> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, SignInResponse>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = SignInResponse.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is SignInResponse && runtimeType == __other.runtimeType) {
      return id == __other.id &&
          email == __other.email &&
          secret == __other.secret;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (id != null) {
      hashCode = hashCode * 31 + id.hashCode;
    }

    if (email != null) {
      hashCode = hashCode * 31 + email.hashCode;
    }

    if (secret != null) {
      hashCode = hashCode * 31 + secret.hashCode;
    }

    return hashCode;
  }

  SignInResponse copyWith({
    String? id,
    String? email,
    String? secret,
  }) {
    id ??= this.id;
    email ??= this.email;
    secret ??= this.secret;

    final _copy_id = id;
    final _copy_email = email;
    final _copy_secret = secret;

    return SignInResponse(
      id: _copy_id,
      email: _copy_email,
      secret: _copy_secret,
    );
  }
}
