part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// signInRequest
class SignInRequest {
  String? email;

  String? password;

  SignInRequest({
    this.email,
    this.password,
  });

  @override
  String toString() {
    return 'SignInRequest[email=$email, password=$password, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    email = (json[r'email'] == null) ? null : (json[r'email'] as String?);

    password =
        (json[r'password'] == null) ? null : (json[r'password'] as String?);
  }

  SignInRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (email != null) {
      json[r'email'] = email;
    }
    if (password != null) {
      json[r'password'] = password;
    }
    return json;
  }

  static List<SignInRequest> listFromJson(List<dynamic>? json) {
    return json == null
        ? <SignInRequest>[]
        : json.map((value) => SignInRequest.fromJson(value)).toList();
  }

  static Map<String, SignInRequest> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, SignInRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = SignInRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is SignInRequest && runtimeType == __other.runtimeType) {
      return email == __other.email && password == __other.password;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (email != null) {
      hashCode = hashCode * 31 + email.hashCode;
    }

    if (password != null) {
      hashCode = hashCode * 31 + password.hashCode;
    }

    return hashCode;
  }

  SignInRequest copyWith({
    String? email,
    String? password,
  }) {
    email ??= this.email;
    password ??= this.password;

    final _copy_email = email;
    final _copy_password = password;

    return SignInRequest(
      email: _copy_email,
      password: _copy_password,
    );
  }
}
