part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// SignupRequest
class SignupRequest {
  String? id;
  String? email;
  String? password;
  String? birthdate;
  String? gender;
  num?    height;
  String? complexion;
  String? education;
  String? country;

  SignupRequest({
    this.id,
    this.email,
    this.password,
    this.birthdate,
    this.gender,
    this.height,
    this.complexion,
    this.education,
    this.country,
  });

  @override
  String toString() {
    return 'SignupRequest[id=$id, email=$email, password=$password, birthdate=$birthdate, gender=$gender, height=$height, complexion=$complexion, education=$education, country=$country, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    id         = (json[r'id']         == null) ? null: (json[r'id'] as String?);
    email      = (json[r'email']      == null) ? null: (json[r'email'] as String?);
    password   = (json[r'password']   == null) ? null: (json[r'password'] as String?);
    birthdate  = (json[r'birthdate']  == null) ? null: (json[r'birthdate'] as String?);
    gender     = (json[r'gender']     == null) ? null: (json[r'gender'] as String?);
    height     = (json[r'height']     == null) ? null: (json[r'height'] as num?);
    complexion = (json[r'complexion'] == null) ? null: (json[r'complexion'] as String?);
    education  = (json[r'education']  == null) ? null: (json[r'education'] as String?);
    country    = (json[r'country']    == null) ? null: (json[r'country'] as String?);
  }

  SignupRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};

    if (id != null) {
      json[r'id'] = id;
    }
    if (email != null) {
      json[r'email'] = email;
    }
    if (password != null) {
      json[r'password'] = password;
    }
    if (birthdate != null) {
      json[r'birthdate'] = birthdate;
    }
    if (gender != null) {
      json[r'gender'] = gender;
    }
    if (height != null) {
      json[r'height'] = height;
    }
    if (complexion != null) {
      json[r'complexion'] = complexion;
    }
    if (education != null) {
      json[r'education'] = education;
    }
    if (country != null) {
      json[r'country'] = country;
    }
    return json;
  }

  static List<SignupRequest> listFromJson(List<dynamic>? json) {
    return json == null ? <SignupRequest>[] : json.map((value) => SignupRequest.fromJson(value)).toList();
  }

  static Map<String, SignupRequest> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, SignupRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) => map[key] = SignupRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is SignupRequest && runtimeType == __other.runtimeType) {
      return id == __other.id &&
          email == __other.email &&
          password == __other.password &&
          birthdate == __other.birthdate &&
          gender == __other.gender &&
          height == __other.height &&
          complexion == __other.complexion &&
          education == __other.education &&
          country == __other.country;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (id != null) {
      hashCode = hashCode * 31 + id.hashCode;
    }

    if (email != null) {
      hashCode = hashCode * 31 + email.hashCode;
    }

    if (password != null) {
      hashCode = hashCode * 31 + password.hashCode;
    }

    if (birthdate != null) {
      hashCode = hashCode * 31 + birthdate.hashCode;
    }

    if (gender != null) {
      hashCode = hashCode * 31 + gender.hashCode;
    }

    if (height != null) {
      hashCode = hashCode * 31 + height.hashCode;
    }

    if (complexion != null) {
      hashCode = hashCode * 31 + complexion.hashCode;
    }

    if (education != null) {
      hashCode = hashCode * 31 + education.hashCode;
    }

    if (country != null) {
      hashCode = hashCode * 31 + country.hashCode;
    }

    return hashCode;
  }

  SignupRequest copyWith({
    String? id,
    String? email,
    String? password,
    String? birthdate,
    String? gender,
    num? height,
    String? complexion,
    String? education,
    String? country,
  }) {
    id ??= this.id;
    email ??= this.email;
    password ??= this.password;
    birthdate ??= this.birthdate;
    gender ??= this.gender;
    height ??= this.height;
    complexion ??= this.complexion;
    education ??= this.education;
    country ??= this.country;

    final _copy_id = id;
    final _copy_email = email;
    final _copy_password = password;
    final _copy_birthdate = birthdate;
    final _copy_gender = gender;
    final _copy_height = height;
    final _copy_complexion = complexion;
    final _copy_education = education;
    final _copy_country = country;

    return SignupRequest(
      id        : _copy_id,
      email     : _copy_email,
      password  : _copy_password,
      birthdate : _copy_birthdate,
      gender    : _copy_gender,
      height    : _copy_height,
      complexion: _copy_complexion,
      education : _copy_education,
      country   : _copy_country,
    );
  }
}
