part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// updateProfileMainPictureById_request
class UpdateProfileMainPictureByIdRequest {
  String? pictureId;

  UpdateProfileMainPictureByIdRequest({
    this.pictureId,
  });

  @override
  String toString() {
    return 'UpdateProfileMainPictureByIdRequest[pictureId=$pictureId, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    pictureId =
        (json[r'picture_id'] == null) ? null : (json[r'picture_id'] as String?);
  }

  UpdateProfileMainPictureByIdRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (pictureId != null) {
      json[r'picture_id'] = pictureId;
    }
    return json;
  }

  static List<UpdateProfileMainPictureByIdRequest> listFromJson(
      List<dynamic>? json) {
    return json == null
        ? <UpdateProfileMainPictureByIdRequest>[]
        : json
            .map((value) => UpdateProfileMainPictureByIdRequest.fromJson(value))
            .toList();
  }

  static Map<String, UpdateProfileMainPictureByIdRequest> mapFromJson(
      Map<String, dynamic>? json) {
    final map = <String, UpdateProfileMainPictureByIdRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = UpdateProfileMainPictureByIdRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is UpdateProfileMainPictureByIdRequest &&
        runtimeType == __other.runtimeType) {
      return pictureId == __other.pictureId;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (pictureId != null) {
      hashCode = hashCode * 31 + pictureId.hashCode;
    }

    return hashCode;
  }

  UpdateProfileMainPictureByIdRequest copyWith({
    String? pictureId,
  }) {
    pictureId ??= this.pictureId;

    final _copy_pictureId = pictureId;

    return UpdateProfileMainPictureByIdRequest(
      pictureId: _copy_pictureId,
    );
  }
}
