part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// UpdateParticipantRequest
class UpdateParticipantRequest {
  String? id;
  String? profile;
  int?    response;

  UpdateParticipantRequest({
    this.id,
    this.profile,
    this.response,
  });

  @override
  String toString() {
    return 'UpdateParticipantRequest[id=$id, profile=$profile, response=$response, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    id = (json[r'id'] == null) ? null : (json[r'id'] as String?);

    profile = (json[r'profile'] == null) ? null : (json[r'profile'] as String?);

    response = (json[r'response'] == null) ? null : (json[r'response'] as int?);
  }

  UpdateParticipantRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (id != null) {
      json[r'id'] = id;
    }
    if (profile != null) {
      json[r'profile'] = profile;
    }
    if (response != null) {
      json[r'response'] = response;
    }
    return json;
  }

  static List<UpdateParticipantRequest> listFromJson(List<dynamic>? json) {
    return json == null
        ? <UpdateParticipantRequest>[]
        : json
            .map((value) => UpdateParticipantRequest.fromJson(value))
            .toList();
  }

  static Map<String, UpdateParticipantRequest> mapFromJson(
      Map<String, dynamic>? json) {
    final map = <String, UpdateParticipantRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = UpdateParticipantRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is UpdateParticipantRequest &&
        runtimeType == __other.runtimeType) {
      return id == __other.id &&
          profile == __other.profile &&
          response == __other.response;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (id != null) {
      hashCode = hashCode * 31 + id.hashCode;
    }

    if (profile != null) {
      hashCode = hashCode * 31 + profile.hashCode;
    }

    if (response != null) {
      hashCode = hashCode * 31 + response.hashCode;
    }

    return hashCode;
  }

  UpdateParticipantRequest copyWith({
    String? id,
    String? profile,
    int? response,
  }) {
    id ??= this.id;
    profile ??= this.profile;
    response ??= this.response;

    final _copy_id = id;
    final _copy_profile = profile;
    final _copy_response = response;

    return UpdateParticipantRequest(
      id: _copy_id,
      profile: _copy_profile,
      response: _copy_response,
    );
  }
}
