part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// updateProfileSocialInfoById_request
class UpdateProfileSocialInfoByIdRequest {
  String? facebook;

  String? x;

  String? instagram;

  String? tiktok;

  String? website;

  String? phone;

  UpdateProfileSocialInfoByIdRequest({
    this.facebook,
    this.x,
    this.instagram,
    this.tiktok,
    this.website,
    this.phone,
  });

  @override
  String toString() {
    return 'UpdateProfileSocialInfoByIdRequest[facebook=$facebook, x=$x, instagram=$instagram, tiktok=$tiktok, website=$website, phone=$phone, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    facebook = (json[r'facebook'] == null) ? null : (json[r'facebook'] as String?);

    x = (json[r'x'] == null) ? null : (json[r'x'] as String?);

    instagram = (json[r'instagram'] == null) ? null : (json[r'instagram'] as String?);

    tiktok = (json[r'tiktok'] == null) ? null : (json[r'tiktok'] as String?);

    website = (json[r'website'] == null) ? null : (json[r'website'] as String?);

    phone = (json[r'phone'] == null) ? null : (json[r'phone'] as String?);
  }

  UpdateProfileSocialInfoByIdRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (facebook != null) {
      json[r'facebook'] = facebook;
    }
    if (x != null) {
      json[r'x'] = x;
    }
    if (instagram != null) {
      json[r'instagram'] = instagram;
    }
    if (tiktok != null) {
      json[r'tiktok'] = tiktok;
    }
    if (website != null) {
      json[r'website'] = website;
    }
    if (phone != null) {
      json[r'phone'] = phone;
    }
    return json;
  }

  static List<UpdateProfileSocialInfoByIdRequest> listFromJson(List<dynamic>? json) {
    return json == null
        ? <UpdateProfileSocialInfoByIdRequest>[]
        : json.map((value) => UpdateProfileSocialInfoByIdRequest.fromJson(value)).toList();
  }

  static Map<String, UpdateProfileSocialInfoByIdRequest> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, UpdateProfileSocialInfoByIdRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) => map[key] = UpdateProfileSocialInfoByIdRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is UpdateProfileSocialInfoByIdRequest && runtimeType == __other.runtimeType) {
      return facebook == __other.facebook &&
          x == __other.x &&
          instagram == __other.instagram &&
          tiktok == __other.tiktok &&
          website == __other.website &&
          phone == __other.phone;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (facebook != null) {
      hashCode = hashCode * 31 + facebook.hashCode;
    }

    if (x != null) {
      hashCode = hashCode * 31 + x.hashCode;
    }

    if (instagram != null) {
      hashCode = hashCode * 31 + instagram.hashCode;
    }

    if (tiktok != null) {
      hashCode = hashCode * 31 + tiktok.hashCode;
    }

    if (website != null) {
      hashCode = hashCode * 31 + website.hashCode;
    }

    if (phone != null) {
      hashCode = hashCode * 31 + phone.hashCode;
    }

    return hashCode;
  }

  UpdateProfileSocialInfoByIdRequest copyWith({
    String? profileId,
    String? facebook,
    String? x,
    String? instagram,
    String? tiktok,
    String? website,
    String? phone,
  }) {
    facebook ??= this.facebook;
    x ??= this.x;
    instagram ??= this.instagram;
    tiktok ??= this.tiktok;
    website ??= this.website;
    phone ??= this.phone;

    final _copy_facebook = facebook;
    final _copy_x = x;
    final _copy_instagram = instagram;
    final _copy_tiktok = tiktok;
    final _copy_website = website;
    final _copy_phone = phone;

    return UpdateProfileSocialInfoByIdRequest(
      facebook: _copy_facebook,
      x: _copy_x,
      instagram: _copy_instagram,
      tiktok: _copy_tiktok,
      website: _copy_website,
      phone: _copy_phone,
    );
  }
}
