part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// updateProfilePrivacyById_request
class UpdateProfilePrivacyByIdRequest {
  int? privacy;

  UpdateProfilePrivacyByIdRequest({
    this.privacy,
  });

  @override
  String toString() {
    return 'UpdateProfilePrivacyByIdRequest[privacy=$privacy, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    privacy = (json[r'privacy'] == null) ? null : (json[r'privacy'] as int?);
  }

  UpdateProfilePrivacyByIdRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (privacy != null) {
      json[r'privacy'] = privacy;
    }
    return json;
  }

  static List<UpdateProfilePrivacyByIdRequest> listFromJson(
      List<dynamic>? json) {
    return json == null
        ? <UpdateProfilePrivacyByIdRequest>[]
        : json
            .map((value) => UpdateProfilePrivacyByIdRequest.fromJson(value))
            .toList();
  }

  static Map<String, UpdateProfilePrivacyByIdRequest> mapFromJson(
      Map<String, dynamic>? json) {
    final map = <String, UpdateProfilePrivacyByIdRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = UpdateProfilePrivacyByIdRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is UpdateProfilePrivacyByIdRequest &&
        runtimeType == __other.runtimeType) {
      return privacy == __other.privacy;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (privacy != null) {
      hashCode = hashCode * 31 + privacy.hashCode;
    }

    return hashCode;
  }

  UpdateProfilePrivacyByIdRequest copyWith({
    int? privacy,
  }) {
    privacy ??= this.privacy;

    final _copy_privacy = privacy;

    return UpdateProfilePrivacyByIdRequest(
      privacy: _copy_privacy,
    );
  }
}
