part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// UpdateEventById_request
class UpdateEventByIdRequest {
  String? profile;
  String? title;
  String? description;
  String? descriptionExtend;
  String? date;
  String? hourInit;
  num? duration;
  num? price;
  int? paxes;
  int? externalPaxes;
  String? poi;
  int? sendToBlocked;
  int? requestValuation;
  int? filterToPreferences;
  int? validateRequest;

  UpdateEventByIdRequest(
      {this.profile,
      this.title,
      this.description,
      this.descriptionExtend,
      this.date,
      this.hourInit,
      this.duration,
      this.price,
      this.paxes,
      this.externalPaxes,
      this.poi,
      this.sendToBlocked,
      this.requestValuation,
      this.filterToPreferences,
      this.validateRequest});

  @override
  String toString() {
    return 'UpdateEventByIdRequest[profile=$profile, title=$title, description=$description, description_extend=$descriptionExtend, date=$date, hourInit=$hourInit, duration=$duration, price=$price, paxes=$paxes, externalPaxes=$externalPaxes, poi=$poi, sendToBlocked=$sendToBlocked, requestValuation=$requestValuation, filterToPreferences=$filterToPreferences, validateRequest=$validateRequest]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    profile = (json[r'profile'] == null) ? null : (json[r'profile'] as String?);
    title = (json[r'title'] == null) ? null : (json[r'title'] as String?);
    description = (json[r'description'] == null) ? null : (json[r'description'] as String?);
    descriptionExtend = (json[r'description_extend'] == null) ? null : (json[r'description_extend'] as String?);
    date = (json[r'date'] == null) ? null : (json[r'date'] as String?);
    hourInit = (json[r'hour_init'] == null) ? null : (json[r'hour_init'] as String?);
    duration = (json[r'duration'] == null) ? null : (json[r'duration'] as num?);
    price = (json[r'price'] == null) ? null : (json[r'price'] as num?);
    paxes = (json[r'paxes'] == null) ? null : (json[r'paxes'] as int?);
    externalPaxes = (json[r'external_paxes'] == null) ? null : (json[r'external_paxes'] as int?);
    poi = (json[r'location'] == null) ? null : (json[r'poi'] as String?);
    sendToBlocked = (json[r'send_to_blocked'] == null) ? null : (json[r'send_to_blocked'] as int?);
    requestValuation = (json[r'request_valuation'] == null) ? null : (json[r'request_valuation'] as int?);
    filterToPreferences = (json[r'filter_to_preferences'] == null) ? null : (json[r'filter_to_preferences'] as int?);
    validateRequest = (json[r'validate_request'] == null) ? null : (json[r'validate_request'] as int?);
  }

  UpdateEventByIdRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (profile != null) {
      json[r'profile'] = profile;
    }
    if (title != null) {
      json[r'title'] = title;
    }
    if (description != null) {
      json[r'description'] = description;
    }
    if (descriptionExtend != null) {
      json[r'description_extend'] = descriptionExtend;
    }
    if (date != null) {
      json[r'date'] = date;
    }
    if (hourInit != null) {
      json[r'hour_init'] = hourInit;
    }
    if (duration != null) {
      json[r'duration'] = duration;
    }
    if (price != null) {
      json[r'price'] = price;
    }
    if (paxes != null) {
      json[r'paxes'] = paxes;
    }
    if (externalPaxes != null) {
      json[r'external_paxes'] = externalPaxes;
    }
    if (poi != null) {
      json[r'poi'] = poi;
    }
    if (sendToBlocked != null) {
      json[r'send_to_blocked'] = sendToBlocked;
    }
    if (requestValuation != null) {
      json[r'request_valuation'] = requestValuation;
    }
    if (filterToPreferences != null) {
      json[r'filter_to_preferences'] = filterToPreferences;
    }
    if (validateRequest != null) {
      json[r'validate_request'] = validateRequest;
    }
    return json;
  }

  static List<UpdateEventByIdRequest> listFromJson(List<dynamic>? json) {
    return json == null
        ? <UpdateEventByIdRequest>[]
        : json.map((value) => UpdateEventByIdRequest.fromJson(value)).toList();
  }

  static Map<String, UpdateEventByIdRequest> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, UpdateEventByIdRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) => map[key] = UpdateEventByIdRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is UpdateEventByIdRequest && runtimeType == __other.runtimeType) {
      return profile == __other.profile &&
          title == __other.title &&
          description == __other.description &&
          descriptionExtend == __other.descriptionExtend &&
          date == __other.date &&
          hourInit == __other.hourInit &&
          duration == __other.duration &&
          price == __other.price &&
          paxes == __other.paxes &&
          externalPaxes == __other.externalPaxes &&
          poi == __other.poi &&
          sendToBlocked == __other.sendToBlocked &&
          requestValuation == __other.requestValuation &&
          filterToPreferences == __other.filterToPreferences &&
          validateRequest == __other.validateRequest;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (profile != null) {
      hashCode = hashCode * 31 + profile.hashCode;
    }

    if (title != null) {
      hashCode = hashCode * 31 + title.hashCode;
    }

    if (description != null) {
      hashCode = hashCode * 31 + description.hashCode;
    }

    if (descriptionExtend != null) {
      hashCode = hashCode * 31 + descriptionExtend.hashCode;
    }

    if (date != null) {
      hashCode = hashCode * 31 + date.hashCode;
    }

    if (hourInit != null) {
      hashCode = hashCode * 31 + hourInit.hashCode;
    }

    if (duration != null) {
      hashCode = hashCode * 31 + duration.hashCode;
    }

    if (price != null) {
      hashCode = hashCode * 31 + price.hashCode;
    }

    if (paxes != null) {
      hashCode = hashCode * 31 + paxes.hashCode;
    }

    if (externalPaxes != null) {
      hashCode = hashCode * 31 + externalPaxes.hashCode;
    }

    if (poi != null) {
      hashCode = hashCode * 31 + poi.hashCode;
    }

    if (sendToBlocked != null) {
      hashCode = hashCode * 31 + sendToBlocked.hashCode;
    }

    if (requestValuation != null) {
      hashCode = hashCode * 31 + requestValuation.hashCode;
    }

    if (filterToPreferences != null) {
      hashCode = hashCode * 31 + filterToPreferences.hashCode;
    }

    if (validateRequest != null) {
      hashCode = hashCode * 31 + validateRequest.hashCode;
    }

    return hashCode;
  }

  UpdateEventByIdRequest copyWith(
      {String? profile,
      String? title,
      String? description,
      String? descriptionExtended,
      String? date,
      String? hourInit,
      num? duration,
      num? price,
      int? paxes,
      int? externalPaxes,
      String? poi,
      int? sendToBlocked,
      int? requestValuation,
      int? filterToPreferences,
      int? validateRequest}) {
    profile ??= this.profile;
    title ??= this.title;
    description ??= this.description;
    descriptionExtended ??= this.descriptionExtend;
    date ??= this.date;
    hourInit ??= this.hourInit;
    duration ??= this.duration;
    price ??= this.price;
    paxes ??= this.paxes;
    externalPaxes ??= this.externalPaxes;
    poi ??= this.poi;
    sendToBlocked ??= this.sendToBlocked;
    requestValuation ??= this.requestValuation;
    filterToPreferences ??= this.filterToPreferences;
    validateRequest ?? this.validateRequest;

    final _copy_profile = profile;
    final _copy_title = title;
    final _copy_description = description;
    final _copy_descriptionExtended = descriptionExtended;
    final _copy_date = date;
    final _copy_hourInit = hourInit;
    final _copy_duration = duration;
    final _copy_price = price;
    final _copy_paxes = paxes;
    final _copy_externalPaxes = externalPaxes;
    final _copy_poi = poi;
    final _copy_sendToBlocked = sendToBlocked;
    final _copy_requestValuation = requestValuation;
    final _copy_filterToPreferences = filterToPreferences;
    final _copy_validate_request = validateRequest;

    return UpdateEventByIdRequest(
        profile: _copy_profile,
        title: _copy_title,
        description: _copy_description,
        descriptionExtend: _copy_descriptionExtended,
        date: _copy_date,
        hourInit: _copy_hourInit,
        duration: _copy_duration,
        price: _copy_price,
        paxes: _copy_paxes,
        externalPaxes: _copy_externalPaxes,
        poi: _copy_poi,
        sendToBlocked: _copy_sendToBlocked,
        requestValuation: _copy_requestValuation,
        filterToPreferences: _copy_filterToPreferences,
        validateRequest: _copy_validate_request);
  }
}
