part of komm.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// validateEmail_request
class ValidateEmailRequest {
  String? email;

  ValidateEmailRequest({
    this.email,
  });

  @override
  String toString() {
    return 'ValidateEmailRequest[email=$email, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;

    email = (json[r'email'] == null) ? null : (json[r'email'] as String?);
  }

  ValidateEmailRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (email != null) {
      json[r'email'] = email;
    }
    return json;
  }

  static List<ValidateEmailRequest> listFromJson(List<dynamic>? json) {
    return json == null ? <ValidateEmailRequest>[] : json.map((value) => ValidateEmailRequest.fromJson(value)).toList();
  }

  static Map<String, ValidateEmailRequest> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, ValidateEmailRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) => map[key] = ValidateEmailRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is ValidateEmailRequest && runtimeType == __other.runtimeType) {
      return email == __other.email;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    if (email != null) {
      hashCode = hashCode * 31 + email.hashCode;
    }

    return hashCode;
  }

  ValidateEmailRequest copyWith({
    String? email,
  }) {
    email ??= this.email;

    final _copy_email = email;

    return ValidateEmailRequest(
      email: _copy_email,
    );
  }
}
